import * as yup from "yup";

const SAMPLE_CONTACTS = [
  {
    id: 1,
    name: "Ronald Richards",
    role: "Owner",
    email: "albert@borer.com",
    created_at: "Feb 5, 2021",
    image_url: "https://randomuser.me/api/portraits/med/men/30.jpg",
  },
  {
    id: 2,
    name: "Jacob Jones",
    role: "Owner",
    email: "albert@borer.com",
    created_at: "Feb 5, 2021",
    image_url: "https://randomuser.me/api/portraits/women/30.jpg",
  },
  {
    id: 3,
    name: "Ronald Richards",
    role: "Owner",
    email: "albert@borer.com",
    created_at: "Feb 5, 2021",
    image_url: "https://randomuser.me/api/portraits/med/men/30.jpg",
  },
  {
    id: 4,
    name: "Jacob Jones",
    role: "Owner",
    email: "albert@borer.com",
    created_at: "Feb 5, 2021",
    image_url: "https://randomuser.me/api/portraits/women/30.jpg",
  },
  {
    id: 5,
    name: "Ronald Richards",
    role: "Owner",
    email: "albert@borer.com",
    created_at: "Feb 5, 2021",
    image_url: "https://randomuser.me/api/portraits/med/men/30.jpg",
  },
  {
    id: 6,
    name: "Jacob Jones",
    role: "Owner",
    email: "albert@borer.com",
    created_at: "Feb 5, 2021",
    image_url: "https://randomuser.me/api/portraits/women/30.jpg",
  },
  {
    id: 7,
    name: "Ronald Richards",
    role: "Owner",
    email: "albert@borer.com",
    created_at: "Feb 5, 2021",
    image_url: "https://randomuser.me/api/portraits/med/men/30.jpg",
  },
  {
    id: 8,
    name: "Jacob Jones",
    role: "Owner",
    email: "albert@borer.com",
    created_at: "Feb 5, 2021",
    image_url: "https://randomuser.me/api/portraits/women/30.jpg",
  },
  {
    id: 9,
    name: "Ronald Richards",
    role: "Owner",
    email: "albert@borer.com",
    created_at: "Feb 5, 2021",
    image_url: "https://randomuser.me/api/portraits/med/men/30.jpg",
  },
  {
    id: 10,
    name: "Jacob Jones",
    role: "Owner",
    email: "albert@borer.com",
    created_at: "Feb 5, 2021",
    image_url: "https://randomuser.me/api/portraits/women/30.jpg",
  },
  {
    id: 11,
    name: "Ronald Richards",
    role: "Owner",
    email: "albert@borer.com",
    created_at: "Feb 5, 2021",
    image_url: "https://randomuser.me/api/portraits/med/men/30.jpg",
  },
  {
    id: 12,
    name: "Jacob Jones",
    role: "Owner",
    email: "albert@borer.com",
    created_at: "Feb 5, 2021",
    image_url: "https://randomuser.me/api/portraits/women/30.jpg",
  },
  {
    id: 13,
    name: "Ronald Richards",
    role: "Owner",
    email: "albert@borer.com",
    created_at: "Feb 5, 2021",
    image_url: "https://randomuser.me/api/portraits/med/men/30.jpg",
  },
  {
    id: 14,
    name: "Jacob Jones",
    role: "Owner",
    email: "albert@borer.com",
    created_at: "Feb 5, 2021",
    image_url: "https://randomuser.me/api/portraits/women/30.jpg",
  },
  {
    id: 15,
    name: "Ronald Richards",
    role: "Owner",
    email: "albert@borer.com",
    created_at: "Feb 5, 2021",
    image_url: "https://randomuser.me/api/portraits/med/men/30.jpg",
  },
  {
    id: 16,
    name: "Jacob Jones",
    role: "Owner",
    email: "albert@borer.com",
    created_at: "Feb 5, 2021",
    image_url: "https://randomuser.me/api/portraits/women/30.jpg",
  },
  {
    id: 17,
    name: "Ronald Richards",
    role: "Owner",
    email: "albert@borer.com",
    created_at: "Feb 5, 2021",
    image_url: "https://randomuser.me/api/portraits/med/men/30.jpg",
  },
  {
    id: 18,
    name: "Jacob Jones",
    role: "Owner",
    email: "albert@borer.com",
    created_at: "Feb 5, 2021",
    image_url: "https://randomuser.me/api/portraits/women/30.jpg",
  },
  {
    id: 19,
    name: "Ronald Richards",
    role: "Owner",
    email: "albert@borer.com",
    created_at: "Feb 5, 2021",
    image_url: "https://randomuser.me/api/portraits/med/men/30.jpg",
  },
  {
    id: 20,
    name: "Jacob Jones",
    role: "Owner",
    email: "albert@borer.com",
    created_at: "Feb 5, 2021",
    image_url: "https://randomuser.me/api/portraits/women/30.jpg",
  },
];

const INITIAL_FORM_VALUES = {
  firstName: "",
  lastName: "",
  email: "",
  role: null,
};

const ROLE_OPTIONS = [
  { id: 1, name: "designer" },
  { id: 2, name: "analyst" },
];

const VALIDATION_SCHEMA = yup.object().shape({
  firstName: yup.string().required(),
  lastName: yup.string().required(),
  email: yup.string().email().required(),
  role: yup.object().nullable().required(),
});

export {
  SAMPLE_CONTACTS,
  INITIAL_FORM_VALUES,
  ROLE_OPTIONS,
  VALIDATION_SCHEMA,
};
