const SAMPLE_CONTACTS = [
  {
    name: "Ronald Richards",
    role: "Owner",
    email: "albert@borer.com",
    created_at: "Feb 5, 2021",
    image_url: "https://randomuser.me/api/portraits/med/men/30.jpg",
  },
  {
    name: "Jacob Jones",
    role: "Owner",
    email: "albert@borer.com",
    created_at: "Feb 5, 2021",
    image_url: "https://randomuser.me/api/portraits/women/30.jpg",
  },
  {
    name: "Ronald Richards",
    role: "Owner",
    email: "albert@borer.com",
    created_at: "Feb 5, 2021",
    image_url: "https://randomuser.me/api/portraits/med/men/30.jpg",
  },
  {
    name: "Jacob Jones",
    role: "Owner",
    email: "albert@borer.com",
    created_at: "Feb 5, 2021",
    image_url: "https://randomuser.me/api/portraits/women/30.jpg",
  },
  {
    name: "Ronald Richards",
    role: "Owner",
    email: "albert@borer.com",
    created_at: "Feb 5, 2021",
    image_url: "https://randomuser.me/api/portraits/med/men/30.jpg",
  },
  {
    name: "Jacob Jones",
    role: "Owner",
    email: "albert@borer.com",
    created_at: "Feb 5, 2021",
    image_url: "https://randomuser.me/api/portraits/women/30.jpg",
  },
  {
    name: "Ronald Richards",
    role: "Owner",
    email: "albert@borer.com",
    created_at: "Feb 5, 2021",
    image_url: "https://randomuser.me/api/portraits/med/men/30.jpg",
  },
  {
    name: "Jacob Jones",
    role: "Owner",
    email: "albert@borer.com",
    created_at: "Feb 5, 2021",
    image_url: "https://randomuser.me/api/portraits/women/30.jpg",
  },
  {
    name: "Ronald Richards",
    role: "Owner",
    email: "albert@borer.com",
    created_at: "Feb 5, 2021",
    image_url: "https://randomuser.me/api/portraits/med/men/30.jpg",
  },
  {
    name: "Jacob Jones",
    role: "Owner",
    email: "albert@borer.com",
    created_at: "Feb 5, 2021",
    image_url: "https://randomuser.me/api/portraits/women/30.jpg",
  },
  {
    name: "Ronald Richards",
    role: "Owner",
    email: "albert@borer.com",
    created_at: "Feb 5, 2021",
    image_url: "https://randomuser.me/api/portraits/med/men/30.jpg",
  },
  {
    name: "Jacob Jones",
    role: "Owner",
    email: "albert@borer.com",
    created_at: "Feb 5, 2021",
    image_url: "https://randomuser.me/api/portraits/women/30.jpg",
  },
  {
    name: "Ronald Richards",
    role: "Owner",
    email: "albert@borer.com",
    created_at: "Feb 5, 2021",
    image_url: "https://randomuser.me/api/portraits/med/men/30.jpg",
  },
  {
    name: "Jacob Jones",
    role: "Owner",
    email: "albert@borer.com",
    created_at: "Feb 5, 2021",
    image_url: "https://randomuser.me/api/portraits/women/30.jpg",
  },
  {
    name: "Ronald Richards",
    role: "Owner",
    email: "albert@borer.com",
    created_at: "Feb 5, 2021",
    image_url: "https://randomuser.me/api/portraits/med/men/30.jpg",
  },
  {
    name: "Jacob Jones",
    role: "Owner",
    email: "albert@borer.com",
    created_at: "Feb 5, 2021",
    image_url: "https://randomuser.me/api/portraits/women/30.jpg",
  },
  {
    name: "Ronald Richards",
    role: "Owner",
    email: "albert@borer.com",
    created_at: "Feb 5, 2021",
    image_url: "https://randomuser.me/api/portraits/med/men/30.jpg",
  },
  {
    name: "Jacob Jones",
    role: "Owner",
    email: "albert@borer.com",
    created_at: "Feb 5, 2021",
    image_url: "https://randomuser.me/api/portraits/women/30.jpg",
  },
  {
    name: "Ronald Richards",
    role: "Owner",
    email: "albert@borer.com",
    created_at: "Feb 5, 2021",
    image_url: "https://randomuser.me/api/portraits/med/men/30.jpg",
  },
  {
    name: "Jacob Jones",
    role: "Owner",
    email: "albert@borer.com",
    created_at: "Feb 5, 2021",
    image_url: "https://randomuser.me/api/portraits/women/30.jpg",
  },
];

export { SAMPLE_CONTACTS };
